name: Node.js CI

on:
  push:
    branches: [ release_js_udfs/* ]
  pull_request:
    branches: [ release_js_udfs/* ]

jobs:
  build:
    environment: ci
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true