name: Node.js CI

on:
  push:
    branches: 
      - 'main'
      - 'releases/**'
      - 'feature/**'
  pull_request:
    branches:
      - 'main'
      - 'releases/**'
      - 'feature/**'
jobs:
    build:
      runs-on: self-hosted-ubuntu
      permissions:
        contents: read
        actions: read
        packages: write
        pull-requests: write
        repository-projects: write
      steps:
       - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          path: source-repo
          
        - name: Slack notify
          id: slack_notify
          uses: 8398a7/action-slack@v3
          if: ${{ always() }}
          with:
            status: ${{ job.status }}
            fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
          env:
            SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
