name: Node.js CI

on:
  push:
    branches: 
      - 'main'
      - 'releases/**'
      - 'feature/**'
  pull_request:
    branches:
      - 'main'
      - 'releases/**'
      - 'feature/**'
jobs:
    build:
      runs-on: self-hosted-ubuntu
      permissions:
        contents: read
        actions: read
        packages: write
        pull-requests: write
        repository-projects: write
      steps:
       - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          path: source-repo